reviews:
  namespace: opsta-dev
  image: bigdev2000/reviews
  tag: dev
  replicas: 1
  imagePullSecrets: default-token-r2ttf
  port: 9080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: reviews.dev.big-bookinfo.opsta.in.th
  path: "/reviews(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  COMMIT_ID: CHANGE_ME