apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.reviews.namespace }}
spec :
  type: {{ .Values.ingress.serviceType }}
  ports:
  - port: {{ .Values.reviews.port }}
    targetPort: {{ .Values.reviews.port }}
  selector:
    app: {{ .Release.Name }}
